import axios from "axios";
import apiConfig from "../config/apiConfig";

export const getColaboradorDetalles = async () => {
    try {
        const idSede = localStorage.getItem("id_sede"); // ‚Üê obtener din√°micamente
        const response = await axios.get(`${apiConfig.baseUrl}/dashboard/coordSedeOverview`, {
          params: { id_sede: idSede },
        });
        return response.data;
      } catch (error) {
        console.error("Error en servicio DashboardSedeService:", error);
        throw error;
      }
};

export const postAceptarColaborador = async (idAplicante, datos) => {
  try {
    console.log("üì§ POST a:", `${apiConfig.baseUrl}/sedes/${idAplicante}/postulaciones/aceptar`);
    console.log("üì¶ Cuerpo del POST:", datos);

    await axios.post(`${apiConfig.baseUrl}/sedes/${idAplicante}/postulaciones/aceptar`, datos);
  } catch (error) {
    console.error("‚ùó Error al intentar aceptar la postulaci√≥n del colaborador:", error);
    if (error.response?.data?.error) {
      throw new Error(error.response.data.error);
    }
    throw new Error("Ocurri√≥ un error al aceptar la postulaci√≥n del colaborador");
  }
};

export const postRechazarColaborador = async (idAplicante, datos) => {
  try {
    await axios.post(`${apiConfig.baseUrl}/sedes/${idAplicante}/postulaciones/rechazar`, datos);
  } catch (error) {
    console.error("Error al intentar rechazar la postulaci√≥n del colaborador:", error);
    if (error.response?.data?.error) {
      throw new Error(error.response.data.error);
    }
    throw new Error("Ocurri√≥ un error al rechazar la postulaci√≥n del colaborador");
  }
};